<?php

return [
    'worker_url' => rtrim((string) env('BROWSER_WORKER_URL', 'http://browser-worker:8081'), '/'),
    'worker_control_secret' => (string) env('WORKER_CONTROL_SECRET', ''),
    'service_auth_secret' => (string) env('RUNTIME_SERVICE_AUTH_SECRET', ''),
    'operator_auth_secret' => (string) env('RUNTIME_OPERATOR_AUTH_SECRET', ''),
    'service_auth_max_skew_seconds' => (int) env('SERVICE_AUTH_MAX_SKEW_SECONDS', 300),
    'service_rate_limit_per_minute' => (int) env('SERVICE_RATE_LIMIT_PER_MINUTE', 600),
    'operator_rate_limit_per_minute' => (int) env('OPERATOR_RATE_LIMIT_PER_MINUTE', 60),
    'api_request_max_bytes' => (int) env('RUNTIME_API_MAX_REQUEST_BYTES', 327680),
    'viewer_signing_secret' => (string) env('VIEWER_SIGNING_SECRET', ''),
    'viewer_token_ttl_seconds' => (int) env('VIEWER_TOKEN_TTL_SECONDS', 300),
    'admin_viewer_token_ttl_seconds' => (int) env('ADMIN_VIEWER_TOKEN_TTL_SECONDS', 900),
    'viewer_public_base_url' => rtrim((string) env('VIEWER_PUBLIC_BASE_URL', 'http://127.0.0.1:18081'), '/'),
    'max_browser_sessions' => (int) env('MAX_BROWSER_SESSIONS', 3),
    'navigation_timeout_ms' => (int) env('BROWSER_NAVIGATION_TIMEOUT_MS', 45000),
    'session_lease_seconds' => (int) env('SESSION_LEASE_SECONDS', 5400),
    'session_idle_timeout_seconds' => (int) env('SESSION_IDLE_TIMEOUT_SECONDS', 900),
    'session_disconnect_grace_seconds' => (int) env('SESSION_DISCONNECT_GRACE_SECONDS', 180),
    'session_startup_grace_seconds' => (int) env('SESSION_STARTUP_GRACE_SECONDS', 30),
    'session_reaper_interval_seconds' => (int) env('SESSION_REAPER_INTERVAL_SECONDS', 30),
    'tool_profiles_path' => (string) env('TOOL_PROFILES_PATH', base_path('config/tool-profiles.json')),
    'browser_state_max_bytes' => (int) env('BROWSER_STATE_MAX_BYTES', 262144),
];
